### ISSUE TITLE
Could it possible to simplify the query string?

### ISSUE THREAD

**Issue by HaveF** [cbti-rj/strapi-graphql-transform#1]
I want to know what did you do when query?

Its a bit annoying(data , attributes things) to query graphql in v4 format = =; 

Thanks for your advice!

**Comment by HaveF** [comment]
I suppose there is not exist solution about this... just find [the forum complain info](https://forum.strapi.io/t/discussion-regarding-the-complex-response-structure-for-rest-graphql-developer-experience/13400/12)

Too sad, but it seems If one want to use graphql in v4, waiting is a reasonable solution 😢

**Comment by cbti-rj** [comment]
I am working on a helper to build this queries without so much boilerplate, I will post here when I have something.
@HaveF
